# Generated by Django 3.1.3 on 2020-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized_images/')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
